<?php
$L=lang();
$t=[
'fa'=>['eyebrow'=>'کتابخانه دیجیتال OMH','title'=>'دانش را پیدا کن، مطالعه کن و به اشتراک بگذار','sub'=>'یک کتابخانه گسترده برای منابع اسلامی، حنفی، آموزشی و علوم عصری؛ با فهرست منظم کتاب‌ها، مؤلفین و موضوعات.','placeholder'=>'نام کتاب، مؤلف، علم یا کلیدواژه را جستجو کنید…','search'=>'جستجوی کتابخانه','enter'=>'ورود به کتابخانه','authors'=>'فهرست مؤلفین','submit'=>'ارسال کتاب','intro'=>'درباره کتابخانه','intro2'=>'کتابخانه عمرمختار هاشمی برای جمع‌آوری، معرفی، دسته‌بندی و دسترسی منظم به منابع ساخته شده است. هدف، ایجاد یک محیط حرفه‌ای و قابل اعتماد برای طلبه، محصل، پژوهشگر و علاقه‌مند است؛ جایی که کتاب، مؤلف، علم، جلد و منبع در یک ساختار روشن کنار هم قرار بگیرند.','sciences'=>'علوم و موضوعات','featured'=>'کتاب‌های ویژه','popular'=>'پربازدیدترین کتاب‌ها','updated'=>'کتاب‌های به‌روز شده','writers'=>'مؤلفین','all'=>'مشاهده همه','random'=>'پیشنهاد کتاب','randomText'=>'یک انتخاب تصادفی از مجموعه کتابخانه برای شما.','open'=>'مشاهده کتاب','quick'=>'دسترسی سریع'],
'ps'=>['eyebrow'=>'د OMH ډیجیټل کتابتون','title'=>'پوهه پیدا کړه، ولوله او شریکه یې کړه','sub'=>'د اسلامي، حنفي، ښوونیزو او عصري علومو لپاره پراخ کتابتون؛ د کتابونو، لیکوالانو او موضوعاتو منظم فهرست.','placeholder'=>'د کتاب نوم، لیکوال، علم یا کلیمه ولټوئ…','search'=>'د کتابتون لټون','enter'=>'کتابتون ته ننوتل','authors'=>'د لیکوالانو فهرست','submit'=>'کتاب ولېږئ','intro'=>'د کتابتون په اړه','intro2'=>'د عمرمختار هاشمي کتابتون د سرچینو د راټولولو، پېژندنې، وېش او منظم لاسرسي لپاره جوړ شوی. موخه یې د طالب العلم، زده کوونکي، څېړونکي او هر لوستونکي لپاره مسلکي او منظم چاپېریال برابرول دي.','sciences'=>'علوم او موضوعات','featured'=>'ځانګړي کتابونه','popular'=>'ډېر کتل شوي کتابونه','updated'=>'تازه شوي کتابونه','writers'=>'لیکوالان','all'=>'ټول وګورئ','random'=>'د کتاب وړاندیز','randomText'=>'ستاسو لپاره د کتابتون له ټولګې څخه یو تصادفي انتخاب.','open'=>'کتاب وګورئ','quick'=>'چټک لاسرسی'],
'ar'=>['eyebrow'=>'مكتبة OMH الرقمية','title'=>'اكتشف المعرفة، اقرأ وشارك','sub'=>'مكتبة واسعة للمصادر الإسلامية والحنفية والتعليمية والعلوم العصرية، مع فهرسة منظمة للكتب والمؤلفين والموضوعات.','placeholder'=>'ابحث باسم الكتاب أو المؤلف أو العلم أو الكلمة…','search'=>'بحث في المكتبة','enter'=>'دخول إلى المكتبة','authors'=>'فهرس المؤلفين','submit'=>'إرسال كتاب','intro'=>'عن المكتبة','intro2'=>'أنشئت مكتبة عمرمختار هاشمي لجمع المصادر وتعريفها وتصنيفها وإتاحة الوصول إليها بصورة منظمة. والهدف هو توفير بيئة احترافية للطالب والباحث وكل محب للعلم، بحيث ترتبط بيانات الكتاب والمؤلف والعلم والمجلد والمصدر في بنية واضحة.','sciences'=>'العلوم والموضوعات','featured'=>'كتب مميزة','popular'=>'الأكثر مشاهدة','updated'=>'الكتب المحدثة','writers'=>'المؤلفون','all'=>'عرض الكل','random'=>'اقتراح كتاب','randomText'=>'اختيار عشوائي من مجموعة المكتبة لك.','open'=>'عرض الكتاب','quick'=>'الوصول السريع'],
'en'=>['eyebrow'=>'OMH DIGITAL LIBRARY','title'=>'Discover knowledge. Read. Share.','sub'=>'A growing library for Islamic, Hanafi, educational and modern sciences, with an organized catalog of books, authors and subjects.','placeholder'=>'Search by book, author, subject or keyword…','search'=>'Search Library','enter'=>'Enter Library','authors'=>'Authors Index','submit'=>'Submit a Book','intro'=>'About the Library','intro2'=>'Omar Mokhtar Hashemi Library is built to collect, describe, organize and provide structured access to knowledge. It aims to offer a professional environment for students, researchers and readers, connecting books, authors, subjects, volumes and sources in one clear catalog.','sciences'=>'Sciences & Topics','featured'=>'Featured Books','popular'=>'Most Viewed','updated'=>'Recently Updated','writers'=>'Authors','all'=>'View all','random'=>'Book Recommendation','randomText'=>'A random selection from the library collection.','open'=>'View book','quick'=>'Quick Access']][$L];
?>
<section class="hero-new">
  <div class="hero-glow"></div><div class="hero-main"><span class="eyebrow"><?=$t['eyebrow']?></span><h1><?=$t['title']?></h1><p><?=$t['sub']?></p>
  <form class="hero-search" action="/search"><input name="q" placeholder="<?=e($t['placeholder'])?>"><button>⌕ <?=$t['search']?></button></form>
  <div class="hero-actions"><a class="btn-gold" href="/books">📖 <?=$t['enter']?></a><a class="btn-ghost" href="/authors">♜ <?=$t['authors']?></a><a class="btn-ghost" href="/submit">＋ <?=$t['submit']?></a></div></div>
  <aside class="hero-emblem"><div class="ornament">ﷲ</div><strong>OMH</strong><span>LIBRARY</span><small>کتابخانه عمرمختار هاشمی</small></aside>
</section>
<section class="intro-new"><div class="section-kicker">✦ <?=e($t['intro'])?> ✦</div><h2><?=$t['intro']?></h2><p><?=$t['intro2']?></p><div class="intro-lines"><span>☾ Islamic Knowledge</span><span>✦ Hanafi Studies</span><span>⌘ Modern Sciences</span><span>▤ Education</span></div></section>
<section class="quick-section"><div class="section-head-new"><div><span class="tiny-label">OMH LIBRARY</span><h2><?=$t['quick']?></h2></div></div><div class="quick-grid"><?php foreach($cats as $c): if(!$c['books'])continue; ?><a href="/category?id=<?=$c['id']?>" class="quick-card"><span class="quick-icon">✦</span><div><strong><?=e($c['name'])?></strong><small><?=number_format($c['books'])?> <?= $L==='en'?'books':'کتاب' ?></small></div><b>←</b></a><?php endforeach; ?></div></section>
<?php if($featured): ?><section><div class="section-head-new"><div><span class="tiny-label">SELECTED COLLECTION</span><h2><?=$t['featured']?></h2></div><div class="slider-controls"><button onclick="document.querySelector('#featured').scrollBy({left:-280,behavior:'smooth'})">‹</button><button onclick="document.querySelector('#featured').scrollBy({left:280,behavior:'smooth'})">›</button></div></div><div class="slider slider-new" id="featured"><?php foreach($featured as $b): ?><a class="mini-book-new" href="/book?id=<?=$b['id']?>"><div class="cover-new"><span>OMH</span><i>📖</i></div><strong><?=e($b['title'])?></strong><small><?=e($b['author']??'')?></small></a><?php endforeach;?></div></section><?php endif; ?>
<section><div class="section-head-new"><div><span class="tiny-label">READERS' CHOICE</span><h2><?=$t['popular']?></h2></div></div><div class="table table-new"><div class="thead"><span># / <?=$t['popular']?></span><span>مؤلف</span><span>بازدید</span></div><?php foreach($popular as $i=>$b):?><a class="tr" href="/book?id=<?=$b['id']?>"><span><b class="rank"><?=str_pad($i+1,2,'0',STR_PAD_LEFT)?></b><?=e($b['title'])?></span><span><?=e($b['author']??'—')?></span><span><?=number_format($b['views'])?> 👁</span></a><?php endforeach;?></div></section>
<section><div class="section-head-new"><div><span class="tiny-label">LIBRARY UPDATES</span><h2><?=$t['updated']?></h2></div></div><div class="table table-new"><div class="thead"><span>کتاب</span><span>مؤلف</span><span>تاریخ</span></div><?php foreach($updated as $b):?><a class="tr" href="/book?id=<?=$b['id']?>"><span><?=e($b['title'])?></span><span><?=e($b['author']??'—')?></span><span><?=date('Y/m/d',strtotime($b['updated_at']))?></span></a><?php endforeach;?></div></section>
<section class="writers-new"><div class="section-head-new"><div><span class="tiny-label">PEOPLE OF KNOWLEDGE</span><h2><?=$t['writers']?></h2></div><a href="/authors" class="all-link"><?=$t['all']?> ←</a></div><div class="author-grid-new"><?php foreach($authors as $a):?><a href="/author?id=<?=$a['id']?>"><span>♜</span><strong><?=e($a['name'])?></strong><small><?=number_format($a['books'])?> <?= $L==='en'?'books':'کتاب' ?></small></a><?php endforeach;?></div></section>
