<?php
$settings=[];try{foreach(OMH\DB::all('SELECT key,value FROM settings') as $s)$settings[$s['key']]=$s['value'];}catch(Throwable $e){}
$site=$settings['site_name']??'OMH Library | کتابخانه عمرمختار هاشمی';$L=lang();
$welcome=['fa'=>$settings['welcome_fa']??'به کتابخانه عمرمختار هاشمی خوش آمدید 🥀','ps'=>$settings['welcome_ps']??'د عمرمختار هاشمي کتابتون ته ښه راغلاست 🥀','ar'=>$settings['welcome_ar']??'مرحباً بكم في مكتبة عمرمختار هاشمي 🥀','en'=>$settings['welcome_en']??'Welcome to Omar Mokhtar Hashemi Library 🥀'][$L]??'';
$topicTree=[];try{$allTopics=OMH\DB::all("SELECT id,parent_id,name,section,sort_order FROM categories WHERE active=true ORDER BY section,sort_order,name");foreach($allTopics as $t)$topicTree[(int)($t['parent_id']??0)][]=$t;}catch(Throwable $e){}
function render_topic_tree($tree,$parent=0,$level=0){if(empty($tree[$parent]))return;echo '<div class="topic-level level-'.$level.'">';foreach($tree[$parent] as $t){$children=!empty($tree[(int)$t['id']]);echo '<div class="topic-item">'.($children?'<button type="button" class="topic-toggle" aria-expanded="false">+</button>':'<span class="topic-spacer"></span>').'<a href="/category?id='.(int)$t['id'].'">'.e($t['name']).'</a>';if($children){echo '<div class="topic-children" hidden>';render_topic_tree($tree,(int)$t['id'],$level+1);echo '</div>';}echo '</div>'; }echo '</div>';}
?>
<!doctype html><html lang="<?=e($L)?>" dir="<?=($L==='en'?'ltr':'rtl')?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c1724"><meta name="description" content="<?=e($settings['site_intro']??'کتابخانه دیجیتال عمرمختار هاشمی')?>"><meta property="og:title" content="<?=e($title??$site)?>"><meta property="og:description" content="<?=e($settings['site_intro']??'کتابخانه دیجیتال عمرمختار هاشمی')?>"><meta property="og:type" content="website"><title><?=e($title??$site)?> | <?=e($site)?></title><link rel="canonical" href="<?=e(rtrim(envv('APP_URL',''),'/').($_SERVER['REQUEST_URI']??'/'))?>"><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="site-header"><div class="header-main wrap-wide"><button class="corner-menu main-menu-btn" aria-label="منوی اصلی">☰ <span>منو</span></button><a class="brand" href="/"><span class="brand-mark">OMH</span><span><b>OMH Library</b><small>کتابخانه عمرمختار هاشمی</small></span></a><nav class="desktop-nav"><a href="/">خانه</a><a href="/books">کتابخانه</a><a href="/submit">ارسال کتاب</a><a href="/authors">مؤلفین و زندگی‌نامه‌ها</a><a href="/contact">ارتباط با ما</a></nav><div class="header-actions"><a href="/lang?lang=fa">دری</a><a href="/lang?lang=ps">پښتو</a><a href="/lang?lang=ar">العربية</a><a href="/lang?lang=en">EN</a><button class="theme-btn" type="button" aria-label="تغییر حالت">☼</button></div><button class="corner-menu topic-menu-btn" aria-expanded="false">☷ <span>موضوعات</span></button></div>
<div class="mobile-nav"><a href="/">خانه</a><a href="/books">کتابخانه</a><a href="/submit">ارسال کتاب</a><a href="/authors">مؤلفین</a><a href="/contact">ارتباط با ما</a></div>
<div class="topic-drawer"><div class="drawer-head"><strong>موضوعات کتابخانه</strong><button type="button" class="drawer-close">×</button></div><?php render_topic_tree($topicTree); ?></div>
<div class="welcome-bar"><div class="marquee-inner"><?=e($welcome)?> &nbsp; • &nbsp; <?=e($site)?></div></div></header>
<main class="wrap-wide main-content"><?php if($flash): ?><div class="flash <?=$flash[0]?>" role="status"><?=e($flash[1])?></div><?php endif; ?><?=$content?></main>
<footer class="site-footer"><section class="footer-topics wrap-wide"><div class="footer-title"><span>📚</span><div><h3>موضوعات و علوم</h3><p>دسترسی سریع به بخش‌های کتابخانه</p></div></div><div class="topic-columns"><?php foreach($topicTree[0]??[] as $tc): ?><a href="/category?id=<?=$tc['id']?>"><?=e($tc['name'])?></a><?php endforeach; ?></div></section><div class="footgrid wrap-wide"><div><h3>OMH Library</h3><p><?=e($settings['site_intro']??'مرجع دیجیتال کتاب، علوم اسلامی، فنون درسی، کتاب‌های مکتب و علوم عصری.')?></p><div class="footer-badges"><span>دری</span><span>پښتو</span><span>العربية</span><span>English</span></div></div><div><h3>دسترسی سریع</h3><a href="/">خانه</a><a href="/books">کتابخانه</a><a href="/submit">ارسال کتاب</a><a href="/authors">مؤلفین و زندگی‌نامه‌ها</a><a href="/contact">ارتباط با ما</a></div><div><h3>بخش‌های کتابخانه</h3><a href="/books?section=curriculum">فنون درسی</a><a href="/books?section=school">کتاب‌های مکتب</a><a href="/books?section=modern">علوم عصری</a><a href="/books?mine=1">کتاب‌های من</a></div><div><h3>ارتباط و قوانین</h3><a href="/sources">منابع و کتابخانه‌های اسلامی</a><a href="/contact#sites">سایت‌های من</a><a href="/contact#feedback">بازخورد و پیشنهاد</a><a href="/legal">حقوق نشر و قوانین</a><a href="/sitemap.xml">نقشه سایت</a></div></div><div class="copy wrap-wide">© <?=date('Y')?> OMH Library — کتابخانه عمرمختار هاشمی · لوگر، افغانستان · با تشکر و دعای خیر شما</div></footer><script>window.OMH={themeKey:'omh-theme'};</script><script src="/assets/js/app.js" defer></script><script>if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});</script></body></html>
