<div class="adminhead"><h1><?=e($title)?></h1><a href="/admin/books">بازگشت</a></div>
<form class="formbox" method="post" action="/admin/book/save" enctype="multipart/form-data">
<?=csrf_field()?>
<input type="hidden" name="id" value="<?=e($b['id']??0)?>">
<label>نام کتاب<input name="title" value="<?=e($b['title']??'')?>" required></label>
<label>مؤلف<select name="author_id"><option value="0">بدون مؤلف</option><?php foreach($authors as $a):?><option value="<?=$a['id']?>" <?=($a['id']==($b['author_id']??0)?'selected':'')?>><?=e($a['name'])?></option><?php endforeach;?></select></label>
<div class="two"><label>زبان<input name="language_code" value="<?=e($b['language_code']??'fa')?>"></label><label>تعداد جلد<input type="number" min="1" name="volumes" value="<?=e($b['volumes']??1)?>"></label></div>
<div class="two"><label>مترجم<input name="translator" value="<?=e($b['translator']??'')?>"></label><label>صفحات<input type="number" min="0" name="pages" value="<?=e($b['pages']??'')?>"></label></div>
<div class="two"><label>سال نشر<input name="publication_year" value="<?=e($b['publication_year']??'')?>"></label><label>ناشر<input name="publisher" value="<?=e($b['publisher']??'')?>"></label></div>
<div class="two"><label>نام منبع<input name="source_name" value="<?=e($b['source_name']??'')?>"></label><label>لینک منبع<input type="url" name="source_url" value="<?=e($b['source_url']??'')?>"></label></div>
<label>معرفی کوتاه<textarea name="description" rows="5"><?=e($b['description']??'')?></textarea></label>
<label>شرح و توضیحات کامل<textarea name="full_description" rows="9"><?=e($b['full_description']??'')?></textarea></label>
<label>کلیدواژه‌ها<input name="keywords" value="<?=e($b['keywords']??'')?>" placeholder="با کاما جدا کنید"></label>
<label>کاور اصلی<input type="file" name="cover" accept="image/jpeg,image/png,image/webp"></label>
<div class="two"><label>وضعیت<select name="status"><option value="published" <?=($b['status']??'published')==='published'?'selected':''?>>منتشرشده</option><option value="draft" <?=($b['status']??'')==='draft'?'selected':''?>>پیش‌نویس</option></select></label><label>ترتیب مدیریتی<input type="number" name="admin_order" value="<?=e($b['admin_order']??0)?>"></label></div>
<div class="two"><label>ترتیب ویژه<input type="number" name="featured_order" value="<?=e($b['featured_order']??0)?>"></label><label><input type="checkbox" name="show_downloads" <?=(!isset($b)||!empty($b['show_downloads']))?'checked':''?>> نمایش شمارنده دانلود</label></div>
<div class="checks"><label><input type="checkbox" name="featured" <?=!empty($b['featured'])?'checked':''?>> کتاب ویژه</label><label><input type="checkbox" name="is_my_book" <?=!empty($b['is_my_book'])?'checked':''?>> کتاب من</label></div>
<h3>علوم و دسته‌بندی‌ها</h3><div class="catchecks"><?php foreach($cats as $c):?><label><input type="checkbox" name="categories[]" value="<?=$c['id']?>" <?=in_array($c['id'],$selected)?'checked':''?>> <?=e($c['name'])?> <small><?=e($c['section'])?></small></label><?php endforeach;?></div>
<h3>روابط علمی کتاب</h3><div class="relation-admin"><?php foreach($relations as $r):?><div class="relation-row"><select name="related_book_id[]"><option value="0">انتخاب کتاب</option><?php foreach($books as $ob):?><option value="<?=$ob['id']?>" <?=($ob['id']==$r['related_book_id'])?'selected':''?>><?=e($ob['title'])?></option><?php endforeach;?></select><select name="relation_type[]"><option value="commentary" <?=($r['relation_type']==='commentary')?'selected':''?>>شرح</option><option value="annotation" <?=($r['relation_type']==='annotation')?'selected':''?>>حاشیه/تعلیقه</option><option value="volume" <?=($r['relation_type']==='volume')?'selected':''?>>مرتبط با جلد/نسخه</option><option value="related" <?=($r['relation_type']==='related')?'selected':''?>>مرتبط</option></select></div><?php endforeach;?><div class="relation-row"><select name="related_book_id[]"><option value="0">انتخاب کتاب دیگر</option><?php foreach($books as $ob):?><option value="<?=$ob['id']?>"><?=e($ob['title'])?></option><?php endforeach;?></select><select name="relation_type[]"><option value="commentary">شرح</option><option value="annotation">حاشیه/تعلیقه</option><option value="related">مرتبط</option></select></div></div>
<h3>جلدها و منابع</h3><p class="muted">برای هر جلد می‌توانید PDF داخلی یا لینک مستقیم منبع را ثبت کنید. فایل PDF حداکثر ۵۰MB است.</p>
<div class="volumes-admin"><?php foreach($vols as $v):?><div class="volume-admin"><input type="hidden" name="volume_id[]" value="<?=$v['id']?>"><label>شماره جلد<input type="number" name="volume_no[]" value="<?=$v['volume_no']?>" min="1"></label><label>صفحات<input type="number" name="volume_pages[]" value="<?=e($v['pages']??'')?>" min="0"></label><label>لینک مستقیم<input type="url" name="external_url[]" value="<?=e($v['external_url']??'')?>"></label><label>PDF جدید<input type="file" name="volume_pdf[]" accept="application/pdf"></label></div><?php endforeach; if(!$vols):?><div class="volume-admin"><input type="hidden" name="volume_id[]" value="0"><label>شماره جلد<input type="number" name="volume_no[]" value="1" min="1"></label><label>صفحات<input type="number" name="volume_pages[]" min="0"></label><label>لینک مستقیم<input type="url" name="external_url[]"></label><label>PDF<input type="file" name="volume_pdf[]" accept="application/pdf"></label></div><?php endif;?></div>
<button class="btn">ذخیره کامل کتاب</button></form>
