<?php namespace OMH;
class Admin{
 static function guard(){if(empty($_SESSION['admin_id'])){redirect('/admin/login');}}
 static function loginForm(){View::render('admin/login',['title'=>'ورود مدیریت']);}
 static function login(){check_csrf();$email=trim($_POST['email']??'');$pass=$_POST['password']??'';if(!empty($_SESSION['login_try'])&&time()-$_SESSION['login_try']<2){sleep(2);}$_SESSION['login_try']=time();$a=DB::one('SELECT * FROM admins WHERE email=?',[$email]);if(!$a||!password_verify($pass,$a['password_hash'])){flash('error','ایمیل یا رمز عبور نادرست است.');return redirect('/admin/login');}session_regenerate_id(true);$_SESSION['admin_id']=$a['id'];$_SESSION['admin_role']=$a['role'];redirect('/admin');}
 static function logout(){unset($_SESSION['admin_id'],$_SESSION['admin_role']);redirect('/admin/login');}
 static function dashboard(){self::guard();$stats=[];foreach(['books'=>'SELECT COUNT(*) FROM books','volumes'=>'SELECT COALESCE(SUM(volumes),0) FROM books','authors'=>'SELECT COUNT(*) FROM authors','categories'=>'SELECT COUNT(*) FROM categories','submissions'=>'SELECT COUNT(*) FROM submissions WHERE status=\'pending\'','views'=>'SELECT COALESCE(SUM(views),0) FROM books','downloads'=>'SELECT COALESCE(SUM(downloads),0) FROM book_volumes'] as $k=>$q)$stats[$k]=DB::id($q);View::render('admin/dashboard',['title'=>'داشبورد','stats'=>$stats]);}
 static function books(){self::guard();$q=trim($_GET['q']??'');$rows=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.title ILIKE ? ORDER BY b.admin_order,b.updated_at DESC LIMIT 100",['%'.$q.'%']);View::render('admin/books',['title'=>'مدیریت کتاب‌ها','rows'=>$rows,'q'=>$q]);}
 static function bookForm(){self::guard();$id=(int)($_GET['id']??0);$b=$id?DB::one('SELECT * FROM books WHERE id=?',[$id]):null;$authors=DB::all('SELECT id,name FROM authors ORDER BY name');$cats=DB::all('SELECT id,name,section FROM categories WHERE active=true ORDER BY section,sort_order,name');$selected=$id?array_column(DB::all('SELECT category_id FROM book_categories WHERE book_id=?',[$id]),'category_id'):[];View::render('admin/book_form',['title'=>$id?'ویرایش کتاب':'افزودن کتاب','b'=>$b,'authors'=>$authors,'cats'=>$cats,'selected'=>$selected]);}
 static function bookSave(){self::guard();check_csrf();$id=(int)($_POST['id']??0);$data=[trim($_POST['title']??''),(int)($_POST['author_id']??0)?:null,$_POST['language_code']??'fa',max(1,(int)($_POST['volumes']??1)),trim($_POST['description']??''),trim($_POST['full_description']??''),trim($_POST['keywords']??''),$_POST['status']??'published',isset($_POST['featured']),max(0,(int)($_POST['featured_order']??0)),max(0,(int)($_POST['admin_order']??0)),isset($_POST['is_my_book'])];if($data[0]===''){flash('error','نام کتاب الزامی است.');return redirect('/admin/book/edit'.($id?'?id='.$id:''));}
  if($id)DB::exec('UPDATE books SET title=?,author_id=?,language_code=?,volumes=?,description=?,full_description=?,keywords=?,status=?,featured=?,featured_order=?,admin_order=?,is_my_book=?,updated_at=NOW() WHERE id=?',array_merge($data,[$id]));else{$id=(int)DB::id('INSERT INTO books(title,author_id,language_code,volumes,description,full_description,keywords,status,featured,featured_order,admin_order,is_my_book,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW()) RETURNING id', $data);}
  DB::exec('DELETE FROM book_categories WHERE book_id=?',[$id]);foreach(($_POST['categories']??[]) as $cid)DB::exec('INSERT INTO book_categories(book_id,category_id) VALUES(?,?) ON CONFLICT DO NOTHING',[$id,(int)$cid]);flash('ok','کتاب ذخیره شد.');redirect('/admin/books');}
 static function bookDelete(){self::guard();check_csrf();DB::exec('DELETE FROM books WHERE id=?',[(int)($_POST['id']??0)]);flash('ok','کتاب حذف شد.');redirect('/admin/books');}
 static function categories(){self::guard();$rows=DB::all('SELECT c.*,p.name parent FROM categories c LEFT JOIN categories p ON p.id=c.parent_id ORDER BY c.section,c.sort_order,c.name');View::render('admin/categories',['title'=>'علوم و دسته‌بندی‌ها','rows'=>$rows]);}
 static function categorySave(){self::guard();check_csrf();$id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$parent=(int)($_POST['parent_id']??0)?:null;$section=$_POST['section']??'science';$active=isset($_POST['active']);$slug=substr(md5($section.$name.microtime(true)),0,16);if($id)DB::exec('UPDATE categories SET name=?,parent_id=?,section=?,active=?,updated_at=NOW() WHERE id=?',[$name,$parent,$section,$active,$id]);else DB::exec('INSERT INTO categories(name,slug,parent_id,section,active) VALUES(?,?,?,?,?)',[$name,$slug,$parent,$section,$active]);redirect('/admin/categories');}
 static function categoryDelete(){self::guard();check_csrf();DB::exec('DELETE FROM categories WHERE id=?',[(int)($_POST['id']??0)]);redirect('/admin/categories');}
 static function authors(){self::guard();$rows=DB::all('SELECT a.*,COUNT(b.id) books FROM authors a LEFT JOIN books b ON b.author_id=a.id GROUP BY a.id ORDER BY a.name');View::render('admin/authors',['title'=>'مؤلفین','rows'=>$rows]);}
 static function authorSave(){self::guard();check_csrf();$id=(int)($_POST['id']??0);$d=[trim($_POST['name']??''),trim($_POST['full_name']??''),trim($_POST['biography']??''),trim($_POST['teachers']??''),trim($_POST['students']??''),trim($_POST['works']??''),trim($_POST['birth_year']??''),trim($_POST['death_year']??''),trim($_POST['location']??'')];if($id)DB::exec('UPDATE authors SET name=?,full_name=?,biography=?,teachers=?,students=?,works=?,birth_year=?,death_year=?,location=?,updated_at=NOW() WHERE id=?',array_merge($d,[$id]));else DB::exec('INSERT INTO authors(name,full_name,biography,teachers,students,works,birth_year,death_year,location) VALUES(?,?,?,?,?,?,?,?,?)',$d);redirect('/admin/authors');}
 static function authorDelete(){self::guard();check_csrf();DB::exec('DELETE FROM authors WHERE id=?',[(int)($_POST['id']??0)]);redirect('/admin/authors');}
 static function submissions(){self::guard();$rows=DB::all('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 200');View::render('admin/submissions',['title'=>'ارسال‌های کتاب','rows'=>$rows]);}
 static function submissionStatus(){self::guard();check_csrf();$id=(int)($_POST['id']??0);DB::exec('UPDATE submissions SET status=?,admin_note=?,updated_at=NOW() WHERE id=?',[$_POST['status']??'pending',trim($_POST['admin_note']??''),$id]);redirect('/admin/submissions');}
 static function settings(){self::guard();$rows=DB::all('SELECT * FROM settings ORDER BY key');View::render('admin/settings',['title'=>'تنظیمات','rows'=>$rows]);}
 static function settingsSave(){self::guard();check_csrf();foreach($_POST['settings']??[] as $k=>$v)DB::exec('INSERT INTO settings(key,value,updated_at) VALUES(?,?,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()',[$k,$v]);redirect('/admin/settings');}
 static function featured(){self::guard();$rows=DB::all("SELECT b.id,b.title,b.featured,b.featured_order FROM books b WHERE b.status='published' ORDER BY b.featured DESC,b.featured_order,b.title");View::render('admin/featured',['title'=>'کتاب‌های ویژه','rows'=>$rows]);}
 static function featuredSave(){self::guard();check_csrf();$ids=$_POST['featured']??[];DB::exec('UPDATE books SET featured=false');foreach($ids as $i=>$id)DB::exec('UPDATE books SET featured=true,featured_order=? WHERE id=?',[$i,(int)$id]);redirect('/admin/featured');}
 static function seed(){self::guard();require __DIR__.'/../database/seed.php';flash('ok','کتاب‌های نمونه و دسته‌بندی‌ها وارد شدند.');redirect('/admin');}
}
