<?php namespace OMH;
class Admin{
 static function guard($write=false){if(empty($_SESSION['admin_id'])){redirect('/admin/login');}if($write&&!in_array($_SESSION['admin_role']??'', ['super_admin','editor'],true)){http_response_code(403);exit('Forbidden');}}
 static function loginForm(){View::render('admin/login',['title'=>'ورود مدیریت']);}
 static function forgotForm(){View::render('admin/forgot',['title'=>'بازیابی رمز مدیریت']);}
 static function forgot(){check_csrf();$email=strtolower(trim($_POST['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL)){flash('error','ایمیل معتبر نیست.');return redirect('/admin/forgot');}$a=DB::one('SELECT * FROM admins WHERE email=? AND active=true',[$email]);if(!$a){flash('ok','اگر این ایمیل متعلق به مدیر باشد، لینک بازیابی ارسال خواهد شد.');return redirect('/admin/login');}if(!empty($_SESSION['reset_try'])&&time()-$_SESSION['reset_try']<60){flash('error','لطفاً یک دقیقه بعد دوباره تلاش کنید.');return redirect('/admin/forgot');}$_SESSION['reset_try']=time();$raw=bin2hex(random_bytes(32));$hash=hash('sha256',$raw);DB::exec("INSERT INTO password_resets(admin_id,token_hash,expires_at) VALUES(?,?,NOW()+INTERVAL '30 minutes')",[$a['id'],$hash]);$base=rtrim(envv('APP_URL',''),'/');$link=$base.'/admin/reset?token='.$raw;$subject='OMH Library — بازیابی رمز مدیریت';$body="برای تغییر رمز مدیریت از لینک زیر استفاده کنید:

$link

این لینک تا ۳۰ دقیقه معتبر است.";if(function_exists('mail'))@mail($email,$subject,$body,'From: '.envv('ADMIN_EMAIL',$email));flash('ok','اگر ایمیل معتبر باشد، لینک بازیابی به ایمیل مدیر ارسال شد.');redirect('/admin/login');}
 static function resetForm(){ $token=preg_replace('/[^a-f0-9]/','',$_GET['token']??'');$ok=$token!==''&&DB::one("SELECT id FROM password_resets WHERE token_hash=? AND expires_at>NOW() AND used_at IS NULL",[hash('sha256',$token)]);View::render('admin/reset',['title'=>'تغییر رمز مدیریت','token'=>$token,'valid'=>(bool)$ok]);}
 static function reset(){check_csrf();$token=preg_replace('/[^a-f0-9]/','',$_POST['token']??'');$pass=$_POST['password']??'';$confirm=$_POST['password_confirm']??'';if($pass!==$confirm){flash('error','تکرار رمز یکسان نیست.');return redirect('/admin/reset?token='.$token);}if(strlen($pass)<10){flash('error','رمز جدید باید حداقل ۱۰ کاراکتر باشد.');return redirect('/admin/reset?token='.$token);} $r=DB::one("SELECT * FROM password_resets WHERE token_hash=? AND expires_at>NOW() AND used_at IS NULL",[hash('sha256',$token)]);if(!$r){flash('error','لینک بازیابی معتبر یا فعال نیست.');return redirect('/admin/login');}DB::exec('UPDATE admins SET password_hash=?,updated_at=NOW() WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$r['admin_id']]);DB::exec('UPDATE password_resets SET used_at=NOW() WHERE id=?',[$r['id']]);flash('ok','رمز مدیریت تغییر کرد.');redirect('/admin/login');}
 static function login(){check_csrf();$email=strtolower(trim($_POST['email']??''));$pass=$_POST['password']??'';if(!empty($_SESSION['login_try'])&&time()-$_SESSION['login_try']<2){sleep(2);}$_SESSION['login_try']=time();$a=DB::one('SELECT * FROM admins WHERE email=? AND active=true',[$email]);if(!$a||!password_verify($pass,$a['password_hash'])){flash('error','ایمیل یا رمز عبور نادرست است.');return redirect('/admin/login');}session_regenerate_id(true);$_SESSION['admin_id']=$a['id'];$_SESSION['admin_role']=$a['role'];DB::exec('UPDATE admins SET last_login_at=NOW() WHERE id=?',[$a['id']]);redirect('/admin');}
 static function logout(){unset($_SESSION['admin_id'],$_SESSION['admin_role']);session_regenerate_id(true);redirect('/admin/login');}
 static function dashboard(){self::guard();$stats=[];foreach(['books'=>'SELECT COUNT(*) FROM books','titles'=>'SELECT COUNT(*) FROM books WHERE status=\'published\'','volumes'=>'SELECT COALESCE(SUM(volumes),0) FROM books','authors'=>'SELECT COUNT(*) FROM authors','categories'=>'SELECT COUNT(*) FROM categories','submissions'=>'SELECT COUNT(*) FROM submissions WHERE status IN (\'pending\',\'edited_by_admin\')','views'=>'SELECT COALESCE(SUM(views),0) FROM books','downloads'=>'SELECT COALESCE(SUM(downloads),0) FROM books'] as $k=>$q)$stats[$k]=DB::id($q);$pending=DB::all("SELECT id,book_title,status,created_at FROM submissions WHERE status IN ('pending','edited_by_admin') ORDER BY created_at DESC LIMIT 8");View::render('admin/dashboard',['title'=>'داشبورد مدیریت','stats'=>$stats,'pending'=>$pending]);}
 static function books(){self::guard();$q=trim($_GET['q']??'');$rows=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE (?='' OR b.title ILIKE ? OR COALESCE(a.name,'') ILIKE ?) ORDER BY b.admin_order,b.updated_at DESC LIMIT 200",[$q,'%'.$q.'%','%'.$q.'%']);View::render('admin/books',['title'=>'مدیریت کتاب‌ها','rows'=>$rows,'q'=>$q]);}
 static function bookForm(){self::guard();$id=(int)($_GET['id']??0);$b=$id?DB::one('SELECT * FROM books WHERE id=?',[$id]):null;$authors=DB::all('SELECT id,name FROM authors ORDER BY name');$cats=DB::all('SELECT id,name,section,parent_id FROM categories WHERE active=true ORDER BY section,sort_order,name');$selected=$id?array_column(DB::all('SELECT category_id FROM book_categories WHERE book_id=?',[$id]),'category_id'):[];$vols=$id?DB::all('SELECT * FROM book_volumes WHERE book_id=? ORDER BY volume_no',[$id]):[];$books=$id?DB::all('SELECT id,title FROM books WHERE id<>? ORDER BY title LIMIT 500',[$id]):DB::all('SELECT id,title FROM books ORDER BY title LIMIT 500');$relations=$id?DB::all('SELECT related_book_id,relation_type FROM book_relations WHERE book_id=?',[$id]):[];View::render('admin/book_form',['title'=>$id?'ویرایش کتاب':'افزودن کتاب','b'=>$b,'authors'=>$authors,'cats'=>$cats,'selected'=>$selected,'vols'=>$vols,'books'=>$books,'relations'=>$relations]);}
 static function bookSave(){self::guard(true);check_csrf();$id=(int)($_POST['id']??0);try{$title=trim($_POST['title']??'');if($title==='')throw new \RuntimeException('نام کتاب الزامی است.');$author=(int)($_POST['author_id']??0)?:null;$data=[$title,$author,$_POST['language_code']??'fa',max(1,(int)($_POST['volumes']??1)),trim($_POST['translator']??''),max(0,(int)($_POST['pages']??0))?:null,trim($_POST['publication_year']??''),trim($_POST['publisher']??''),trim($_POST['source_name']??''),trim($_POST['source_url']??''),trim($_POST['description']??''),trim($_POST['full_description']??''),trim($_POST['keywords']??''),$_POST['status']??'published',isset($_POST['featured']),max(0,(int)($_POST['featured_order']??0)),max(0,(int)($_POST['admin_order']??0)),isset($_POST['is_my_book']),isset($_POST['show_downloads'])];$cover=upload_file('cover','covers',5242880,['image/jpeg','image/png','image/webp']);if($cover)$data[]=$cover;
 if($id){$sql='UPDATE books SET title=?,author_id=?,language_code=?,volumes=?,translator=?,pages=?,publication_year=?,publisher=?,source_name=?,source_url=?,description=?,full_description=?,keywords=?,status=?,featured=?,featured_order=?,admin_order=?,is_my_book=?,show_downloads=?,updated_at=NOW()';if($cover){$sql.=',cover_path=?';}$sql.=' WHERE id=?';$params=$data;$params[]=$id;DB::exec($sql,$params);}else{$slug=slugify($title).'-'.bin2hex(random_bytes(3));$cols='title,author_id,language_code,volumes,translator,pages,publication_year,publisher,source_name,source_url,description,full_description,keywords,status,featured,featured_order,admin_order,is_my_book,show_downloads,slug,cover_path,created_at,updated_at';$vals='?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW()';$params=$data;array_splice($params,19,0,[$slug,$cover]);$id=(int)DB::id("INSERT INTO books($cols) VALUES($vals) RETURNING id",$params);}
 DB::exec('DELETE FROM book_categories WHERE book_id=?',[$id]);foreach($_POST['categories']??[] as $cid)DB::exec('INSERT INTO book_categories(book_id,category_id) VALUES(?,?) ON CONFLICT DO NOTHING',[$id,(int)$cid]);DB::exec('DELETE FROM book_relations WHERE book_id=?',[$id]);foreach($_POST['related_book_id']??[] as $i=>$rid){$rid=(int)$rid;if($rid&&$rid!==$id){$rtype=trim($_POST['relation_type'][$i]??'related');if(!in_array($rtype,['commentary','annotation','volume','related'],true))$rtype='related';DB::exec('INSERT INTO book_relations(book_id,related_book_id,relation_type) VALUES(?,?,?) ON CONFLICT DO NOTHING',[$id,$rid,$rtype]);}}
 $existing=DB::all('SELECT id,volume_no FROM book_volumes WHERE book_id=?',[$id]);$keep=[];foreach($_POST['volume_no']??[] as $i=>$vn){$vn=max(1,(int)$vn);$vid=(int)($_POST['volume_id'][$i]??0);$ext=trim($_POST['external_url'][$i]??'');$pages=max(0,(int)($_POST['volume_pages'][$i]??0))?:null;$file=null;if(isset($_FILES['volume_pdf']['tmp_name'][$i])&&$_FILES['volume_pdf']['error'][$i]!==UPLOAD_ERR_NO_FILE){$tmp=$_FILES['volume_pdf']['tmp_name'][$i];$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($tmp);if($mime!=='application/pdf'||$_FILES['volume_pdf']['size'][$i]>52428800)throw new \RuntimeException('PDF جلد '.$vn.' نامعتبر یا بزرگ است.');$name='pdfs/'.bin2hex(random_bytes(18)).'.pdf';$dest=__DIR__.'/../uploads/'.$name;move_uploaded_file($tmp,$dest);$file=$name;}$vals=[$vn,'جلد '.$vn,$pages,$ext];if($vid){$sql='UPDATE book_volumes SET volume_no=?,volume_title=?,pages=?,external_url=?,updated_at=NOW()';$params=$vals;if($file){$sql.=',file_path=?';$params[]=$file;}$sql.=' WHERE id=? AND book_id=?';$params[]=$vid;$params[]=$id;DB::exec($sql,$params);$keep[]=$vid;}else{$params=[$id,$vn,'جلد '.$vn,$pages,$file,$ext];$new=(int)DB::id('INSERT INTO book_volumes(book_id,volume_no,volume_title,pages,file_path,external_url,created_at,updated_at) VALUES(?,?,?,?,?,?,NOW(),NOW()) RETURNING id',$params);$keep[]=$new;}}
 if(empty($_POST['volume_no'])){for($vn=1;$vn<=max(1,(int)($_POST['volumes']??1));$vn++)DB::exec('INSERT INTO book_volumes(book_id,volume_no,volume_title,created_at,updated_at) VALUES(?,?,?,NOW(),NOW()) ON CONFLICT(book_id,volume_no) DO NOTHING',[$id,$vn,'جلد '.$vn]);} foreach($existing as $ev)if(!in_array($ev['id'],$keep,true))DB::exec('DELETE FROM book_volumes WHERE id=?',[$ev['id']]);
 DB::exec('INSERT INTO activity_logs(admin_id,action,entity_type,entity_id,details) VALUES(?,?,?,?,?)',[$_SESSION['admin_id'],'save','book',$id,$title]);flash('ok','کتاب ذخیره شد.');redirect('/admin/books');}catch(\Throwable $e){flash('error',$e->getMessage());redirect('/admin/book/edit'.($id?'?id='.$id:''));}}
 static function bookDelete(){self::guard(true);check_csrf();DB::exec('DELETE FROM books WHERE id=?',[(int)($_POST['id']??0)]);redirect('/admin/books');}
 static function categories(){self::guard();$rows=DB::all('SELECT c.*,p.name parent FROM categories c LEFT JOIN categories p ON p.id=c.parent_id ORDER BY c.section,c.sort_order,c.name');$parents=DB::all('SELECT id,name,section FROM categories ORDER BY section,sort_order,name');$edit=(int)($_GET['edit']??0);$editing=$edit?DB::one('SELECT * FROM categories WHERE id=?',[$edit]):null;View::render('admin/categories',['title'=>'علوم و دسته‌بندی‌ها','rows'=>$rows,'parents'=>$parents,'editing'=>$editing]);}
 static function categorySave(){self::guard(true);check_csrf();$id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');if($name==='')return redirect('/admin/categories');$parent=(int)($_POST['parent_id']??0)?:null;$section=$_POST['section']??'science';$active=isset($_POST['active']);$sort=(int)($_POST['sort_order']??0);if($id&&$parent===$id)$parent=null;if($id)DB::exec('UPDATE categories SET name=?,parent_id=?,section=?,active=?,sort_order=?,updated_at=NOW() WHERE id=?',[$name,$parent,$section,$active,$sort,$id]);else DB::exec('INSERT INTO categories(name,slug,parent_id,section,active,sort_order) VALUES(?,?,?,?,?,?)',[$name,slugify($name).'-'.bin2hex(random_bytes(3)),$parent,$section,$active,$sort]);redirect('/admin/categories');}
 static function categoryDelete(){self::guard(true);check_csrf();DB::exec('DELETE FROM categories WHERE id=?',[(int)($_POST['id']??0)]);redirect('/admin/categories');}
 static function authors(){self::guard();$rows=DB::all('SELECT a.*,COUNT(b.id) books FROM authors a LEFT JOIN books b ON b.author_id=a.id GROUP BY a.id ORDER BY a.name');View::render('admin/authors',['title'=>'مؤلفین','rows'=>$rows]);}
 static function authorSave(){self::guard(true);check_csrf();$id=(int)($_POST['id']??0);$d=[trim($_POST['name']??''),trim($_POST['full_name']??''),trim($_POST['biography']??''),trim($_POST['teachers']??''),trim($_POST['students']??''),trim($_POST['works']??''),trim($_POST['birth_year']??''),trim($_POST['death_year']??''),trim($_POST['location']??''),trim($_POST['aliases']??''),trim($_POST['bio_source_url']??'')];if($id)DB::exec('UPDATE authors SET name=?,full_name=?,biography=?,teachers=?,students=?,works=?,birth_year=?,death_year=?,location=?,aliases=?,bio_source_url=?,updated_at=NOW() WHERE id=?',array_merge($d,[$id]));else DB::exec('INSERT INTO authors(name,full_name,biography,teachers,students,works,birth_year,death_year,location,aliases,bio_source_url) VALUES(?,?,?,?,?,?,?,?,?,?,?)',$d);redirect('/admin/authors');}
 static function authorDelete(){self::guard(true);check_csrf();DB::exec('DELETE FROM authors WHERE id=?',[(int)($_POST['id']??0)]);redirect('/admin/authors');}
 static function submissions(){self::guard();$rows=DB::all('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 500');View::render('admin/submissions',['title'=>'ارسال‌های کتاب','rows'=>$rows]);}
 static function submissionStatus(){self::guard(true);check_csrf();$id=(int)($_POST['id']??0);$status=$_POST['status']??'pending';$note=trim($_POST['admin_note']??'');DB::exec('UPDATE submissions SET status=?,admin_note=?,updated_at=NOW(),final_approved_at=CASE WHEN ?=\'approved\' THEN NOW() ELSE final_approved_at END WHERE id=?',[$status,$note,$status,$id]);DB::exec('INSERT INTO submission_events(submission_id,event_type,message) VALUES(?,?,?)',[$id,$status,$note]);redirect('/admin/submissions');}
 static function settings(){self::guard();$rows=DB::all('SELECT * FROM settings ORDER BY key');View::render('admin/settings',['title'=>'تنظیمات','rows'=>$rows]);}
 static function settingsSave(){self::guard(true);check_csrf();foreach($_POST['settings']??[] as $k=>$v){if(!preg_match('/^[a-z0-9_]+$/',$k))continue;DB::exec('INSERT INTO settings(key,value,updated_at) VALUES(?,?,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()',[$k,$v]);}redirect('/admin/settings');}
 static function featured(){self::guard();$rows=DB::all("SELECT b.id,b.title,b.featured,b.featured_order FROM books b WHERE b.status='published' ORDER BY b.featured DESC,b.featured_order,b.title");View::render('admin/featured',['title'=>'کتاب‌های ویژه','rows'=>$rows]);}
 static function featuredSave(){self::guard(true);check_csrf();DB::exec('UPDATE books SET featured=false');$ids=$_POST['featured']??[];$orders=$_POST['featured_order']??[];foreach($ids as $id){$id=(int)$id;$ord=max(0,(int)($orders[$id]??0));DB::exec('UPDATE books SET featured=true,featured_order=? WHERE id=?',[$ord,$id]);}redirect('/admin/featured');}
 static function sources(){self::guard();$rows=DB::all('SELECT * FROM external_sources ORDER BY active DESC,name');View::render('admin/sources',['title'=>'منابع خارجی','rows'=>$rows]);}
 static function sourceSave(){self::guard(true);check_csrf();$id=(int)($_POST['id']??0);$d=[trim($_POST['name']??''),trim($_POST['url']??''),trim($_POST['topic']??''),trim($_POST['language_code']??''),trim($_POST['rights_note']??''),isset($_POST['active'])];if($id)DB::exec('UPDATE external_sources SET name=?,url=?,topic=?,language_code=?,rights_note=?,active=? WHERE id=?',array_merge($d,[$id]));else DB::exec('INSERT INTO external_sources(name,url,topic,language_code,rights_note,active) VALUES(?,?,?,?,?,?)',$d);redirect('/admin/sources');}
 static function sourceDelete(){self::guard(true);check_csrf();DB::exec('DELETE FROM external_sources WHERE id=?',[(int)$_POST['id']]);redirect('/admin/sources');}
 static function sites(){self::guard();$rows=DB::all('SELECT * FROM related_sites ORDER BY sort_order,name');View::render('admin/sites',['title'=>'سایت‌های من','rows'=>$rows]);}
 static function siteSave(){self::guard(true);check_csrf();$id=(int)($_POST['id']??0);$d=[trim($_POST['name']??''),trim($_POST['description']??''),trim($_POST['url']??''),isset($_POST['active']),(int)($_POST['sort_order']??0)];if($id)DB::exec('UPDATE related_sites SET name=?,description=?,url=?,active=?,sort_order=? WHERE id=?',array_merge($d,[$id]));else DB::exec('INSERT INTO related_sites(name,description,url,active,sort_order) VALUES(?,?,?,?,?)',$d);redirect('/admin/sites');}
 static function siteDelete(){self::guard(true);check_csrf();DB::exec('DELETE FROM related_sites WHERE id=?',[(int)$_POST['id']]);redirect('/admin/sites');}
 static function feedback(){self::guard();$rows=DB::all('SELECT * FROM feedback ORDER BY created_at DESC LIMIT 500');View::render('admin/feedback',['title'=>'بازخوردها','rows'=>$rows]);}
 static function feedbackStatus(){self::guard(true);check_csrf();DB::exec('UPDATE feedback SET approved=? WHERE id=?',[(int)isset($_POST['approved']),(int)$_POST['id']]);redirect('/admin/feedback');}
 static function seed(){self::guard(true);require __DIR__.'/../database/seed.php';flash('ok','کاتالوگ اولیه بررسی و تکمیل شد.');redirect('/admin');}
}
