<?php namespace OMH;
class Controllers{
 static function health(){header('Content-Type: application/json');try{DB::id('SELECT 1');echo json_encode(['ok'=>true,'app'=>'OMH Library','time'=>date('c')]);}catch(\Throwable $e){http_response_code(503);echo json_encode(['ok'=>false]);}}
 static function language(){lang();$back=$_SERVER['HTTP_REFERER']??'/';redirect($back);}
 static function home(){
  $cats=DB::all("SELECT c.*,COUNT(DISTINCT CASE WHEN b.status='published' THEN bc.book_id END) books FROM categories c LEFT JOIN book_categories bc ON bc.category_id=c.id LEFT JOIN books b ON b.id=bc.book_id WHERE c.active=true GROUP BY c.id ORDER BY c.section,c.sort_order,c.name");
  $featured=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' AND b.featured=true ORDER BY b.featured_order,b.admin_order,b.id DESC LIMIT 18");
  $popular=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' ORDER BY b.views DESC LIMIT 12");
  $updated=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' ORDER BY b.updated_at DESC LIMIT 12");
  $authors=DB::all("SELECT a.*,COUNT(b.id) books FROM authors a LEFT JOIN books b ON b.author_id=a.id AND b.status='published' GROUP BY a.id ORDER BY a.name LIMIT 20");
  $random=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' ORDER BY RANDOM() LIMIT 1");
  View::render('home',['title'=>'خانه','cats'=>$cats,'featured'=>$featured,'popular'=>$popular,'updated'=>$updated,'authors'=>$authors,'random'=>$random[0]??null]);
 }
 static function books(){self::bookList(null);} static function category(){self::bookList((int)($_GET['id']??0));}
 static function bookList($cat){$page=max(1,(int)($_GET['page']??1));$per=min(100,max(10,(int)($_GET['rows']??20)));$q=trim($_GET['q']??'');$sort=$_GET['sort']??'updated';$order=['updated'=>'b.updated_at DESC','name'=>'b.title ASC','old'=>'b.created_at ASC','views'=>'b.views DESC','downloads'=>'b.downloads DESC'][$sort]??'b.updated_at DESC';$where=["b.status='published'"];$p=[];$title='همه کتاب‌ها';if($cat){$c=DB::one('SELECT * FROM categories WHERE id=? AND active=true',[$cat]);if(!$c)return View::render('404',['title'=>'دسته یافت نشد']);$title=$c['name'];$where[]='EXISTS(SELECT 1 FROM book_categories x WHERE x.book_id=b.id AND x.category_id=?)';$p[]=$cat;}if($q!==''){$n=str_replace(['ي','ى','ك','أ','إ','ٱ'],['ی','ی','ک','ا','ا','ا'],$q);$like='%'.$n.'%';$where[]="(REPLACE(REPLACE(REPLACE(b.title,'ي','ی'),'ك','ک'),'ى','ی') ILIKE ? OR COALESCE(a.name,'') ILIKE ? OR COALESCE(b.keywords,'') ILIKE ?)";array_push($p,$like,$like,$like);} $w=implode(' AND ',$where);$total=(int)DB::id("SELECT COUNT(*) FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE $w",$p);$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$offset=($page-1)*$per;$rows=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE $w ORDER BY $order,b.id DESC LIMIT $per OFFSET $offset",$p);View::render('books',['title'=>$title,'rows'=>$rows,'total'=>$total,'page'=>$page,'pages'=>$pages,'q'=>$q,'sort'=>$sort,'cat'=>$cat]);}
 static function book(){ $id=(int)($_GET['id']??0);$b=DB::one("SELECT b.*,a.name author,a.id author_id FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.id=? AND b.status='published'",[$id]);if(!$b)return View::render('404',['title'=>'کتاب یافت نشد']);DB::exec('UPDATE books SET views=views+1 WHERE id=?',[$id]);DB::exec('INSERT INTO visits(resource_type,resource_id,ip_hash,user_agent) VALUES(?,?,?,?)',['book',$id,client_ip_hash(),$_SERVER['HTTP_USER_AGENT']??'']);$cats=DB::all('SELECT c.* FROM categories c JOIN book_categories bc ON bc.category_id=c.id WHERE bc.book_id=? ORDER BY c.section,c.sort_order,c.name',[$id]);$vols=DB::all('SELECT * FROM book_volumes WHERE book_id=? ORDER BY volume_no',[$id]);$related=DB::all("SELECT DISTINCT b.id,b.title,b.cover_path,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id JOIN book_categories bc ON bc.book_id=b.id WHERE bc.category_id IN (SELECT category_id FROM book_categories WHERE book_id=?) AND b.id<>? AND b.status='published' LIMIT 12",[$id,$id]);View::render('book',['title'=>$b['title'],'b'=>$b,'cats'=>$cats,'vols'=>$vols,'related'=>$related]);}
 static function authors(){ $q=trim($_GET['q']??'');$rows=DB::all("SELECT a.*,COUNT(b.id) books FROM authors a LEFT JOIN books b ON b.author_id=a.id AND b.status='published' WHERE (?='' OR a.name ILIKE ?) GROUP BY a.id ORDER BY a.name LIMIT 100",[$q,'%'.$q.'%']);View::render('authors',['title'=>'مؤلفین و زندگی‌نامه‌ها','rows'=>$rows,'q'=>$q]);}
 static function author(){ $id=(int)($_GET['id']??0);$a=DB::one('SELECT * FROM authors WHERE id=?',[$id]);if(!$a)return View::render('404',['title'=>'مؤلف یافت نشد']);$books=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.author_id=? AND b.status='published' ORDER BY b.title",[$id]);View::render('author',['title'=>$a['name'],'a'=>$a,'books'=>$books]);}
 static function search(){ $q=trim($_GET['q']??'');$types=$_GET['types']??['books','authors','categories'];if(!is_array($types))$types=[$types];$books=$authors=$cats=[];if($q!==''){if(in_array('books',$types,true))$books=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' AND (b.title ILIKE ? OR COALESCE(a.name,'') ILIKE ? OR COALESCE(b.keywords,'') ILIKE ?) ORDER BY b.views DESC LIMIT 100",['%'.$q.'%','%'.$q.'%','%'.$q.'%']);if(in_array('authors',$types,true))$authors=DB::all('SELECT * FROM authors WHERE name ILIKE ? ORDER BY name LIMIT 100',['%'.$q.'%']);if(in_array('categories',$types,true))$cats=DB::all('SELECT * FROM categories WHERE active=true AND name ILIKE ? ORDER BY name LIMIT 100',['%'.$q.'%']);}View::render('search',['title'=>'جستجو','q'=>$q,'books'=>$books,'authors'=>$authors,'cats'=>$cats]);}
 static function submitForm(){View::render('submit',['title'=>'ارسال کتاب']);}
 static function submit(){check_csrf();try{$name=trim($_POST['submitter_name']??'');$email=trim($_POST['email']??'');$title=trim($_POST['book_title']??'');$author=trim($_POST['author']??'');$desc=trim($_POST['description']??'');if($name===''||$title==='')throw new \RuntimeException('نام شما و نام کتاب الزامی است.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new \RuntimeException('ایمیل معتبر نیست.');$token=bin2hex(random_bytes(32));$edit=bin2hex(random_bytes(32));$file=upload_file('pdf','submissions',52428800,['application/pdf']);$cover=upload_file('cover','submission-covers',5242880,['image/jpeg','image/png','image/webp']);DB::exec("INSERT INTO submissions(submitter_name,email,phone,book_title,author_name,description,language_code,publication_year,source_name,copyright_status,file_path,cover_path,external_url,status,tracking_token,edit_token,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',?,?,NOW(),NOW())",[$name,$email,trim($_POST['phone']??''),$title,$author,$desc,$_POST['language_code']??'fa',trim($_POST['publication_year']??''),trim($_POST['source_name']??''),trim($_POST['copyright_status']??''),$file,$cover,trim($_POST['external_url']??''),$token,$edit]);flash('ok','درخواست ثبت شد. کد پیگیری شما: '.$token);redirect('/track?token='.$token);}catch(\Throwable $e){flash('error',$e->getMessage());redirect('/submit');}}
 static function track(){ $t=preg_replace('/[^a-f0-9]/','',$_GET['token']??'');$s=$t?DB::one('SELECT * FROM submissions WHERE tracking_token=? OR edit_token=?',[$t,$t]):null;View::render('track',['title'=>'پیگیری ارسال','s'=>$s]);}
 static function submissionEdit(){check_csrf();$t=preg_replace('/[^a-f0-9]/','',$_POST['token']??'');$s=DB::one('SELECT * FROM submissions WHERE edit_token=? AND status IN (\'pending\',\'edited_by_admin\')',[$t]);if(!$s){flash('error','کد ویرایش معتبر نیست یا درخواست دیگر قابل ویرایش نیست.');return redirect('/track?token='.$t);}DB::exec('UPDATE submissions SET submitter_name=?,email=?,phone=?,book_title=?,author_name=?,description=?,updated_at=NOW() WHERE id=?',[trim($_POST['submitter_name']??''),trim($_POST['email']??''),trim($_POST['phone']??''),trim($_POST['book_title']??''),trim($_POST['author']??''),trim($_POST['description']??''),$s['id']]);flash('ok','درخواست به‌روزرسانی شد.');redirect('/track?token='.$t);}
 static function contact(){View::render('contact',['title'=>'ارتباط با ما','sites'=>DB::all('SELECT * FROM related_sites WHERE active=true ORDER BY sort_order,name')]);}
 static function feedback(){check_csrf();$message=trim($_POST['message']??'');if($message===''){flash('error','پیام خالی است.');return redirect('/contact');}DB::exec('INSERT INTO feedback(name,email,message,approved,created_at) VALUES(?,?,?,false,NOW())',[trim($_POST['name']??''),trim($_POST['email']??''),$message]);flash('ok','پیام شما ثبت شد و پس از بررسی مدیریت نمایش داده می‌شود.');redirect('/contact');}
 static function legal(){View::render('legal',['title'=>'قوانین و حقوق نشر']);}
 static function reader(){ $id=(int)($_GET['id']??0);$v=DB::one("SELECT v.*,b.title FROM book_volumes v JOIN books b ON b.id=v.book_id WHERE v.id=? AND b.status='published'",[$id]);if(!$v||!$v['file_path'])return View::render('404',['title'=>'نسخه خواندن در دسترس نیست']);View::render('reader',['title'=>'مطالعه | '.$v['title'],'v'=>$v]);}
 static function download(){ $id=(int)($_GET['id']??0);$v=DB::one('SELECT * FROM book_volumes WHERE id=?',[$id]);if(!$v){http_response_code(404);exit('Not found');}DB::exec('UPDATE book_volumes SET downloads=downloads+1 WHERE id=?',[$id]);DB::exec('UPDATE books SET downloads=downloads+1 WHERE id=?',[$v['book_id']]);DB::exec('INSERT INTO downloads(book_id,volume_id,ip_hash) VALUES(?,?,?)',[$v['book_id'],$id,client_ip_hash()]);if($v['external_url']&&filter_var($v['external_url'],FILTER_VALIDATE_URL))redirect($v['external_url']);if($v['file_path']){$path=__DIR__.'/../uploads/'.$v['file_path'];if(is_file($path)){header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.basename($path).'"');header('Content-Length: '.filesize($path));readfile($path);exit;}}http_response_code(404);exit('File unavailable');}
 static function sitemap(){header('Content-Type: application/xml; charset=utf-8');$base=rtrim(envv('APP_URL','http://localhost'),'/');echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach(['/','/books','/authors','/submit','/contact','/legal'] as $u)echo '<url><loc>'.e($base.$u).'</loc></url>';foreach(DB::all("SELECT id,updated_at FROM books WHERE status='published'") as $b)echo '<url><loc>'.e($base.'/book?id='.$b['id']).'</loc><lastmod>'.date('c',strtotime($b['updated_at'])).'</lastmod></url>';echo '</urlset>';}
 static function robots(){header('Content-Type:text/plain');echo "User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ".rtrim(envv('APP_URL','http://localhost'),'/')."/sitemap.xml\n";}
}
