<?php namespace OMH;
class Controllers{
 static function home(){
  $cats=DB::all("SELECT c.*,COUNT(bc.book_id) books FROM categories c LEFT JOIN book_categories bc ON bc.category_id=c.id LEFT JOIN books b ON b.id=bc.book_id AND b.status='published' WHERE c.active=true GROUP BY c.id ORDER BY c.sort_order,c.name");
  $featured=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' AND b.featured=true ORDER BY b.featured_order,b.id DESC LIMIT 12");
  $popular=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' ORDER BY b.views DESC LIMIT 8");
  $updated=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' ORDER BY b.updated_at DESC LIMIT 8");
  $authors=DB::all("SELECT a.*,COUNT(b.id) books FROM authors a LEFT JOIN books b ON b.author_id=a.id AND b.status='published' GROUP BY a.id ORDER BY a.name LIMIT 16");
  View::render('home',['title'=>'خانه','cats'=>$cats,'featured'=>$featured,'popular'=>$popular,'updated'=>$updated,'authors'=>$authors]);
 }
 static function books(){self::bookList(null);}
 static function category(){self::bookList((int)($_GET['id']??0));}
 static function bookList($cat){$page=max(1,(int)($_GET['page']??1));$per=20;$q=trim($_GET['q']??'');$where=["b.status='published'"];$p=[];$title='همه کتاب‌ها';
  if($cat){$c=DB::one("SELECT * FROM categories WHERE id=? AND active=true",[$cat]);if(!$c)return View::render('404',['title'=>'دسته یافت نشد']);$title=$c['name'];$where[]='EXISTS(SELECT 1 FROM book_categories x WHERE x.book_id=b.id AND (x.category_id=? OR x.category_id IN(SELECT id FROM categories WHERE parent_id=?)))';$p[]=$cat;$p[]=$cat;}
  if($q!==''){$where[]='(b.title ILIKE ? OR COALESCE(a.name,\'\') ILIKE ? OR COALESCE(b.keywords,\'\') ILIKE ?)';$like='%'.$q.'%';array_push($p,$like,$like,$like);}
  $w=implode(' AND ',$where);$total=(int)DB::id("SELECT COUNT(*) FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE $w",$p);$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$offset=($page-1)*$per;
  $rows=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE $w ORDER BY b.admin_order,b.updated_at DESC LIMIT $per OFFSET $offset",$p);
  View::render('books',['title'=>$title,'rows'=>$rows,'total'=>$total,'page'=>$page,'pages'=>$pages,'q'=>$q]);
 }
 static function book(){ $id=(int)($_GET['id']??0);$b=DB::one("SELECT b.*,a.name author,a.id author_id FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.id=? AND b.status='published'",[$id]);if(!$b)return View::render('404',['title'=>'کتاب یافت نشد']);DB::exec('UPDATE books SET views=views+1 WHERE id=?',[$id]);$cats=DB::all("SELECT c.* FROM categories c JOIN book_categories bc ON bc.category_id=c.id WHERE bc.book_id=? ORDER BY c.name",[$id]);$vols=DB::all("SELECT * FROM book_volumes WHERE book_id=? ORDER BY volume_no",[$id]);$related=DB::all("SELECT DISTINCT b.id,b.title,b.cover_path,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id JOIN book_categories bc ON bc.book_id=b.id WHERE bc.category_id IN (SELECT category_id FROM book_categories WHERE book_id=?) AND b.id<>? AND b.status='published' LIMIT 8",[$id,$id]);View::render('book',['title'=>$b['title'],'b'=>$b,'cats'=>$cats,'vols'=>$vols,'related'=>$related]); }
 static function authors(){ $q=trim($_GET['q']??'');$rows=DB::all("SELECT a.*,COUNT(b.id) books FROM authors a LEFT JOIN books b ON b.author_id=a.id AND b.status='published' WHERE a.name ILIKE ? GROUP BY a.id ORDER BY a.name LIMIT 100",['%'.$q.'%']);View::render('authors',['title'=>'مؤلفین و زندگی‌نامه‌ها','rows'=>$rows,'q'=>$q]); }
 static function author(){ $id=(int)($_GET['id']??0);$a=DB::one('SELECT * FROM authors WHERE id=?',[$id]);if(!$a)return View::render('404',['title'=>'مؤلف یافت نشد']);$books=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.author_id=? AND b.status='published' ORDER BY b.title",[$id]);View::render('author',['title'=>$a['name'],'a'=>$a,'books'=>$books]); }
 static function search(){ $q=trim($_GET['q']??'');$types=$_GET['types']??['books','authors','categories'];if(!is_array($types))$types=[$types];$books=[];$authors=[];$cats=[];if($q!==''){if(in_array('books',$types))$books=DB::all("SELECT b.*,a.name author FROM books b LEFT JOIN authors a ON a.id=b.author_id WHERE b.status='published' AND (b.title ILIKE ? OR COALESCE(a.name,'') ILIKE ? OR COALESCE(b.keywords,'') ILIKE ?) LIMIT 50",['%'.$q.'%','%'.$q.'%','%'.$q.'%']);if(in_array('authors',$types))$authors=DB::all("SELECT * FROM authors WHERE name ILIKE ? LIMIT 50",['%'.$q.'%']);if(in_array('categories',$types))$cats=DB::all("SELECT * FROM categories WHERE name ILIKE ? LIMIT 50",['%'.$q.'%']);}View::render('search',['title'=>'جستجو','q'=>$q,'books'=>$books,'authors'=>$authors,'cats'=>$cats]); }
 static function submitForm(){View::render('submit',['title'=>'ارسال کتاب']);}
 static function submit(){check_csrf();$name=trim($_POST['submitter_name']??'');$email=trim($_POST['email']??'');$title=trim($_POST['book_title']??'');$author=trim($_POST['author']??'');$desc=trim($_POST['description']??'');if($name===''||$title===''){flash('error','نام شما و نام کتاب الزامی است.');return redirect('/submit');}$token=bin2hex(random_bytes(24));DB::exec("INSERT INTO submissions(submitter_name,email,book_title,author_name,description,status,tracking_token,created_at) VALUES(?,?,?,?,?,'pending',?,NOW())",[$name,$email,$title,$author,$desc,$token]);flash('ok','درخواست شما ثبت شد. کد پیگیری: '.$token);redirect('/submit');}
 static function contact(){View::render('contact',['title'=>'ارتباط با ما']);} static function legal(){View::render('legal',['title'=>'قوانین و حقوق نشر']);}
 static function download(){ $id=(int)($_GET['id']??0);$b=DB::one('SELECT * FROM book_volumes WHERE id=?',[$id]);if(!$b)http_response_code(404) and exit('Not found');DB::exec('UPDATE book_volumes SET downloads=downloads+1 WHERE id=?',[$id]);if($b['external_url'])redirect($b['external_url']);if($b['file_path']){ $path=__DIR__.'/../uploads/'.$b['file_path'];if(is_file($path)){header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.basename($path).'"');readfile($path);exit;}}http_response_code(404);exit('File unavailable'); }
 static function sitemap(){header('Content-Type: application/xml; charset=utf-8');$base=rtrim(envv('APP_URL','http://localhost'),'/');echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach(['/','/books','/authors','/submit','/contact'] as $u)echo '<url><loc>'.e($base.$u).'</loc></url>';foreach(DB::all("SELECT id,updated_at FROM books WHERE status='published'") as $b)echo '<url><loc>'.e($base.'/book?id='.$b['id']).'</loc><lastmod>'.date('c',strtotime($b['updated_at'])).'</lastmod></url>';echo '</urlset>';}
 static function robots(){header('Content-Type:text/plain');echo "User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ".rtrim(envv('APP_URL','http://localhost'),'/')."/sitemap.xml\n";}
}
